openapi: 3.0.3
info:
  title: microservices/content
  description: "API by microservices/content"
  version: 0.0.1

tags:
  - name: spaces
    description: Рабочие пространства
  - name: blocks
    description: Контент для заметок, секции, страницы, абзацы и т.п.

paths:
  /spaces:
    get:
      tags:
        - spaces
      summary: Получить список рабочих пространств
      operationId: getSpaces
      description: Получить список рабочих пространств
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpaceList'
    post:
      tags:
        - spaces
      summary: Создать рабочее пространство
      operationId: createSpace
      description: Создать рабочее пространство
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpaceCreate'
      responses:
        '201':
          description: Успешно создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'

  /spaces/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
        description: Уникальный идентификатор пространства
    get:
      tags:
        - spaces
      summary: Получить рабочее пространство
      operationId: getSpace
      description: Получить рабочее пространство
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'

    put:
      tags:
        - spaces
      summary: Обновить рабочее пространство
      operationId: updateSpace
      description: Сохранить изменения рабочего пространства
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpaceUpdate'
      responses:
        '200':
          description: Успешно обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Space'

  /blocks:
    get:
      tags:
        - blocks
      summary: Получить список блоков контента
      operationId: getBlocks
      description: Получить список блоков контента
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockList'
    post:
      tags:
        - blocks
      summary: Создать блок контента
      operationId: createBlock
      description: Создать страницу
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlockCreate'
      responses:
        '201':
          description: Успешно создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'

  /blocks/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
        description: Уникальный идентификатор блока
    get:
      tags:
        - blocks
      summary: Получить блок контента
      operationId: getBlock
      description: Получить блок контента
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'
                
    put:
      tags:
        - blocks
      summary: Обновить блок контента
      operationId: updateBlock
      description: Отправить на сохранение изменения контента
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlockUpdate'
      responses:
        '200':
          description: Успешно обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Block'

components:
  schemas:
    SpaceList:
      type: array
      items:
        $ref: '#/components/schemas/Space'

    Space:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        owner_user_id:
          type: integer

    SpaceCreate:
      type: object
      properties:
        name:
          type: string
        owner_user_id:
          type: integer

    SpaceUpdate:
      type: object
      properties:
        name:
          type: string

    BlockList:
      type: array
      items:
        $ref: '#/components/schemas/Block'

    Block:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        type:
          type: string
          enum:
            - section
            - page
            - paragraph
        parent_id:
          type: integer
        body:
          type: string
        blocks:
          type: array
          items:
            $ref: '#/components/schemas/Block'

    BlockCreate:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        body:
          type: string
        parent_id:
          type: integer
  
    BlockUpdate:
      type: object
      properties:
        name:
          type: string
        body:
          type: string
