/* tslint:disable */
/* eslint-disable */
/**
 * microservices/core
 * API for core microservice handling spaces and notes
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpaceCreate
 */
export interface SpaceCreate {
    /**
     * 
     * @type {string}
     * @memberof SpaceCreate
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SpaceCreate
     */
    img?: string;
}

/**
 * Check if a given object implements the SpaceCreate interface.
 */
export function instanceOfSpaceCreate(value: object): value is SpaceCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SpaceCreateFromJSON(json: any): SpaceCreate {
    return SpaceCreateFromJSONTyped(json, false);
}

export function SpaceCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpaceCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'img': json['img'] == null ? undefined : json['img'],
    };
}

export function SpaceCreateToJSON(json: any): SpaceCreate {
    return SpaceCreateToJSONTyped(json, false);
}

export function SpaceCreateToJSONTyped(value?: SpaceCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'img': value['img'],
    };
}

